#ifndef MULTIEDITORVARINTS_GLOBAL_H
#define MULTIEDITORVARINTS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MULTIEDITORVARINTS_LIBRARY)
#  define MULTIEDITORVARINTS_EXPORT Q_DECL_EXPORT
#else
#  define MULTIEDITORVARINTS_EXPORT Q_DECL_IMPORT
#endif

#endif // MULTIEDITORVARINTS_GLOBAL_H
